import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1776727537112 implements MigrationInterface {

    name = 'InitialMigration1776727537112';

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS "accounts"`);
        await queryRunner.query(`
            CREATE TABLE "accounts"."users" (
                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "username" CHARACTER VARYING(50) NOT NULL CONSTRAINT "UQ_username" UNIQUE,
                "email" CHARACTER VARYING(255) NOT NULL CONSTRAINT "UQ_email" UNIQUE,
                "password_hash" CHARACTER VARYING(255) NOT NULL,
                "names" CHARACTER VARYING(255) NOT NULL,
                "last_names" CHARACTER VARYING(255),
                "is_active" BOOLEAN NOT NULL DEFAULT true,
                "created_at" TIMESTAMP NOT NULL DEFAULT now(),
                "updated_at" TIMESTAMP NOT NULL DEFAULT now()
            )
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "accounts"."users"`);
        await queryRunner.query(`DROP SCHEMA IF EXISTS "accounts"`);
    }

}
